/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import static org.lwjgl.opengl.GL46C.*;

import org.engine.assets.AssetRegistry;
import org.engine.graphics.Material;
import org.engine.graphics.Mesh;
import org.engine.graphics.Shader;
import org.engine.graphics.Texture;
import org.engine.graphics.Vertex;
import org.engine.io.Input;
import org.engine.io.Window;
import org.engine.scene.Transform;
import org.joml.Matrix4f;
import org.joml.Vector2f;
import org.joml.Vector3f;

public class App {

    public static void main(String[] args) {
        Vertex[] vertices = new Vertex[] {
            new Vertex(
                new Vector3f(0.5f, 0.5f, 0.0f),
                new Vector2f(1.0f, 1.0f)
            ),
            new Vertex(
                new Vector3f(0.5f, -0.5f, 0.0f),
                new Vector2f(1.0f, 0.0f)
            ),
            new Vertex(
                new Vector3f(-0.5f, -0.5f, 0.0f),
                new Vector2f(0.0f, 0.0f)
            ),
            new Vertex(
                new Vector3f(-0.5f, 0.5f, 0.0f),
                new Vector2f(0.0f, 1.0f)
            ),
        };

        Window window = new Window();
        window.open("Test Window");
        int vao = glGenVertexArrays();
        glBindVertexArray(vao);

        new Shader(
            "unlit",
            "resources/shaders/spacial.vert",
            "resources/shaders/unlit.frag"
        ).compile();
        new Shader(
            "unlit_textured",
            "resources/shaders/spacial.vert",
            "resources/shaders/unlit_textured.frag"
        ).compile();

        new Texture("nb", "resources/textures/nb.jpg");

        Mesh mesh = new Mesh();
        mesh.storeVertices(vertices, new int[] { 0, 1, 3, 1, 2, 3 });
        mesh.material = new Material(
            "test material",
            (Shader) AssetRegistry.getAssetByName("unlit_textured")
        );
        mesh.material.setParam("transform", new Matrix4f().identity());
        mesh.material.setParam("albedo", new Vector3f(1.0f, 1.0f, 0.0f));
        mesh.material.setParam("alpha", 1);
        mesh.material.setParam("tex", 0);
        mesh.material.setTextureSlot(
            0,
            (Texture) AssetRegistry.getAssetByName("nb")
        );

        window.loop(dalta -> {
            Input.processPendingInput();
            mesh.draw(new Transform());
        });

        window.close();
    }
}
