/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import org.engine.io.Window;

public class App {

    public static void mainLoop(float deltaTime) {}

    public static void main(String[] args) {
        Window window = new Window();
        window.open("Test Window");
        window.loop(App::mainLoop);
        window.close();
    }
}
