/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import static org.lwjgl.glfw.GLFW.GLFW_KEY_W;
import static org.lwjgl.opengl.GL46C.*;

import org.engine.assets.AssetRegistry;
import org.engine.graphics.Material;
import org.engine.graphics.Mesh;
import org.engine.graphics.Renderable;
import org.engine.graphics.Shader;
import org.engine.graphics.Texture;
import org.engine.graphics.Vertex;
import org.engine.io.Input;
import org.engine.io.Window;
import org.engine.scene.Camera;
import org.engine.scene.Entity;
import org.engine.scene.EntityRegistry;
import org.engine.scene.Model;
import org.engine.scene.Transform;
import org.engine.scene.Tree;
import org.joml.Matrix4f;
import org.joml.Quaternionf;
import org.joml.Vector2f;
import org.joml.Vector3f;

public class App {

    public static void main(String[] args) {
        Window window = new Window();
        window.open("Test Window");
        int vao = glGenVertexArrays();
        glBindVertexArray(vao);

        new Shader(
            "unlit",
            "resources/shaders/spacial.vert",
            "resources/shaders/unlit.frag"
        ).compile();
        new Shader(
            "unlit_textured",
            "resources/shaders/spacial.vert",
            "resources/shaders/unlit_textured.frag"
        ).compile();

        new Texture("nb", "resources/textures/nb.jpg");

        Camera cam = new Camera();
        cam.transform.position.z = -1.0f;
        cam.recomputeMatrices(window);

        Mesh mesh = new Mesh("test");
        mesh.storeVertices(
            Vertex.generateCubeVertices(),
            Vertex.generateCubeIndices()
        );
        mesh.material = new Material(
            "test material",
            (Shader) AssetRegistry.getAssetByName("unlit_textured")
        );
        mesh.material.setParam(
            "transform",
            new Matrix4f().identity().rotateY(2.0f)
        );
        mesh.material.setParam(
            "projection",
            Camera.activeCamera.getProjection()
        );
        mesh.material.setParam("view", Camera.activeCamera.getView());
        mesh.material.setParam("albedo", new Vector3f(1.0f, 1.0f, 0.0f));
        mesh.material.setParam("alpha", 1);
        mesh.material.setParam("tex", 0);
        mesh.material.setTextureSlot(
            0,
            (Texture) AssetRegistry.getAssetByName("nb")
        );

        new Model(mesh);

        glEnable(GL_DEPTH_TEST);

        window.loop(delta -> {
            Input.processPendingInput();
            for (Entity e : Tree.registry.getRegisterdEntities()) {
                if (e instanceof Renderable) ((Renderable) e).draw();
            }
        });

        window.close();
    }
}
